### ISSUE TITLE
undefined method `match' in `multiline_pipe.rb`

### ISSUE THREAD

**Issue by andyw8** [michaelherold/codeclimate-haml_lint#2]
Hi @michaelherold 

Thanks for the fix in #1. Re-running, I ran into this:

```
/usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/linter/multiline_pipe.rb:42:in `check': undefined method `match' for nil:NilClass (NoMethodError)
Did you mean?  catch
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/linter/multiline_pipe.rb:20:in `visit_silent_script'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/haml_visitor.rb:40:in `safe_send'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/haml_visitor.rb:19:in `visit'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/haml_visitor.rb:30:in `block in visit_children'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/haml_visitor.rb:30:in `each'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/haml_visitor.rb:30:in `visit_children'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/haml_visitor.rb:24:in `visit'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/linter.rb:28:in `run'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/runner.rb:84:in `block in collect_lints'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/runner.rb:83:in `map'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/runner.rb:83:in `collect_lints'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/runner.rb:119:in `process_file'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/runner.rb:108:in `block in process_files'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/runner.rb:107:in `each'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/runner.rb:107:in `process_files'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/runner.rb:132:in `report'
	from /usr/local/bundle/gems/haml_lint-0.23.1/lib/haml_lint/runner.rb:23:in `run'
	from /usr/src/app/lib/cc/engine/source_file.rb:64:in `process'
	from /usr/src/app/lib/cc/engine/haml_lint.rb:54:in `block in run'
	from /usr/src/app/lib/cc/engine/haml_lint.rb:48:in `run'
	from /usr/src/app/bin/codeclimate-haml_lint:10:in `<main>'
```

Let me know there any other information I can provide which might help.

**Comment by andyw8** [comment]
Actually, this seems to a bug with haml_lint itself, I get the same failure when running directly. So I'll close this.
